"""empty message

Revision ID: 1fd33bafd4e2
Revises: 0dedf8cda1f3
Create Date: 2023-04-15 16:29:10.599712

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1fd33bafd4e2'
down_revision = '0dedf8cda1f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('postcard', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link', sa.String(length=100), nullable=False))
        batch_op.alter_column('content',
               existing_type=mysql.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('postcard', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.drop_column('link')

    # ### end Alembic commands ###
