"""empty message

Revision ID: 2b76d0beac67
Revises: e9f570d8ce16
Create Date: 2023-05-05 14:46:38.207526

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2b76d0beac67'
down_revision = 'e9f570d8ce16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('index', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sentiment_label', sa.Integer(), nullable=False))
        batch_op.drop_column('sentiment_lable')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('index', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sentiment_lable', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('sentiment_label')

    # ### end Alembic commands ###
