"""empty message

Revision ID: 4f6ea00f5dbc
Revises: c143717b4961
Create Date: 2023-05-05 14:16:53.646258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f6ea00f5dbc'
down_revision = 'c143717b4961'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('index', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['text'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('index', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
