"""empty message

Revision ID: 9551731fe3a3
Revises: 9a26f9639376
Create Date: 2023-05-05 12:43:52.138423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9551731fe3a3'
down_revision = '9a26f9639376'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('index',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sentiment_lable', sa.Integer(), nullable=False),
    sa.Column('sentiment_key', sa.String(length=100), nullable=False),
    sa.Column('positive_probs', sa.Float(), nullable=False),
    sa.Column('negative_probs', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('postcard', schema=None) as batch_op:
        batch_op.add_column(sa.Column('index_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'index', ['index_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('postcard', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('index_id')

    op.drop_table('index')
    # ### end Alembic commands ###
